#!/bin/bash

### Variables

BROWSER='Firefox'
WALLPAPER=$HOME/Wallpapers/plenio.jpg
HOSTNAME=$(cat /etc/hostname)

$HOME/.screenlayout/default.sh
$HOME/.config/polybar/startup.sh

### Configure bspwm

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
# Remove all the rules
bspc rule -r "*"

bspc rule -a discord desktop='Chat'
bspc rule -a Steam desktop='Steam' follow=on focus=on

bspc rule -a $BROWSER -o desktop='Browser Main'

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

# Configure desktops
./desktops.sh

### Auto start programs

$HOME/.screenlayout/default.sh &
$HOME/.config/polybar/startup.sh &

# Start all programs
if ! pgrep "sxhkd" > /dev/null
then
	sxhkd &
fi
if ! pgrep "compton" > /dev/null
then
	compton &
fi
if ! pgrep -x "redshift" > /dev/null
then
	redshift &
fi
if ! pgrep "dunst" > /dev/null
then
	dunst &
fi

discord &

# Auto suspend after 15 minutes
xautolock -time 15 -locker "systemctl suspend" -detectsleep -corners +00- &

wal -a 85 -i $WALLPAPER &

###

