#!/bin/bash

WALLPAPER=$HOME/Wallpapers/plenio.jpg

HOSTNAME=$(cat /etc/hostname)

$HOME/.screenlayout/work.sh
$HOME/.config/polybar/startup.sh

# Start all programs
sxhkd &
if ! pgrep "compton" > /dev/null
then
    compton &
fi
if ! pgrep -x "redshift" > /dev/null
then
    redshift &
fi
dunst &

# Auto suspend after 15 minutes
xautolock -time 15 -locker "systemctl suspend" -detectsleep

wal -a 85 -i $WALLPAPER &

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

if [ $HOSTNAME = "Daniels-Laptop" ]; then
	# if only one monitor
    if [ $(xrandr | grep " connected " | awk '{ print$1 }' | wc -l) = 1 ]; then
        bspc monitor eDP-1 -d Firefox Terminal Misc VM Terminal Firefox Misc
    else
        bspc monitor HDMI-2 -d Firefox Terminal Misc VM
	    bspc monitor eDP-1 -d Terminal Firefox Misc
    fi
else
	bspc monitor DVI-D-0 -d Chat Misc
	bspc monitor DP-0 -d Firefox Misc
	bspc monitor HDMI-0 -d Terminal Firefox Steam
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a discord desktop=$Chat follow=no
bspc rule -a steam desktop=$Steam follow=no
