[cursor]
style = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font.normal]
family = "Hack"

[window]
opacity = 1

general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

